apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kesahptest1-5f16"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kesahptest1-5f16"
  template:
    metadata:
      labels:
        app: "kesahptest1-5f16"
    spec:
      containers:
        - name: "kesahptest1-5f16"
          image: "keshaptestnew2.azurecr.io/kesahptest1"
          ports:
          - containerPort: 8080