apiVersion: v1
kind: Service
metadata:
    name: "kesahptest1-3a95"
    labels:
        app: "kesahptest1-3a95"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "kesahptest1-3a95"