on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n azvotetest2 -g azvotetest29a8f-rg --location "East US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n azvotetest2 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n azvotetest2 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n azvotetest2 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: azvotetest2.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/analytics/1.0" -f  "src/analytics/1.0/Dockerfile" -t azvotetest2.azurecr.io/azurevotetest1:${{ github.sha }} --label dockerfile-path=src/analytics/1.0/Dockerfile
        docker push azvotetest2.azurecr.io/azurevotetest1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_azurevotetest1_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azurevotetest18a17 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azurevotetest18a17`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azurevotetest18a17
        container-registry-url: azvotetest2.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: azurevotetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azurevotetest18a17
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          azvotetest2.azurecr.io/azurevotetest1:${{ github.sha }}
        imagepullsecrets: |
          azurevotetesdockerauth   
